### ISSUE TITLE
Ability to receive XML output from callback (rather than String or JSON)

### ISSUE THREAD

**Issue by m-chandler** [wookoouk/blastjs#1]
For my purposes, it would be useful if the module provided the ability to return raw XML rather than forcing JSON or string output.

It's a trivial improvement - I may submit a pull request in the near future.

**Comment by doomedramen** [comment]
I have no plans to export XML as default.

I would suggest using a library like `xml-js` to convert the json output to XML.

```
var convert = require('xml-js');
var result = convert.json2xml(json, {});
```

**Comment by doomedramen** [comment]
I just browsed through the code and realised I already had this feature blastjs 😊,

calling `blast.stringOutput = true` OR `blast.outputString(true);` should give you the raw output.
